logo: logo.png
avatar: avatar.png
# html lang
language: en



# main menu navigation
menu:
  home: / || fa fa-home  # 首页 (Home)
  archive: /archives || fa fa-archive  # 归档 (Archive)
  categories: /categories || fa fa-th-large  # 分类 (Categories)
  tags: /tags || fa fa-tags  # 标签 (Tags)
  about: /about || fa fa-user  # 关于 (About)
  links: /links || fa fa-link  # 友链 (Links)
  rss: /atom.xml || fa fa-rss  # RSS订阅 (RSS)
  travellings: https://www.travellings.cn/go.html || fa fa-train   # 开往 (Travellings)

social_links:
  Github: https://github.com/xingwangzhe || fab fa-github  # Github链接 (Github Link)
  Twitter: https://twitter.com/|| fab fa-twitter  # Twitter链接 (Twitter Link)
  Facebook: https://www.facebook.com/ || fab fa-facebook-f  # Facebook链接 (Facebook Link)
  YouTube: https://www.youtube.com/ || fab fa-youtube  # YouTube链接 (YouTube Link)
  Bilibili: https://space.bilibili.com/ || fab fa-bilibili  # Bilibili链接 (Bilibili Link)
  QQ: https://im.qq.com/ || fab fa-qq  # QQ链接 (QQ Link)
